var language = {
  appName: "Ürün Katalog",
  login: "Giriş Yap",
  register: "Kayıt Ol",
  email: "E-Posta",
  password: "Parola",
  passwordAgain: "Parola (tekrar)",
  name: "İsim",
  surname: "Soyisim",
  productDetail: "Ürün Detayları",
  en: "İngilizce (English)",
  tr: "Türkçe (Turkish)",
  addProduct: "Ürün Ekle",
  upload: "Yükle",
  save: "Kaydet",
  brand: "Marka",
  picture: "Resim",
  pleasePictureSelect: "Lütfen ürün resminizi seçin",
  category: "Kategori",
  color: "Renk",
  useCase: "Kullanım Durumu",
  select: "Seçiniz...",
  productName: "Ürün İsmi",
  productDescription: "Ürün Açıklaması",
  productPrice: "Ürün Fiyatı",
  yes: "Evet",
  no: "Hayır",
  productIsOfferable: "Teklif Verilebilir",
  productIsSold: "Satıldı",
  ERR_EXTENSION: "Yüklemeye çalıştığınız resmin uzantısı kabul edilmiyor",
  ERR_SIZE: "Yüklemeye çalıştığınız resmin boyutu 400KB'tan büyüktür",
  ERR_PASSWORD_NOT_EQUAL: "Parolalar aynı değil",
  ERR_PASSWORD_SHORT: "Parola kısa",
  ERR_PASSWORD_LONG: "Parola uzun",
  logout: "Çıkış yap",
  sendOffer: "Teklif Ver",
  buy: "Satın Al",
  priceSign: "$",
  user: "Kullanıcı",
  myAccount: "Hesabım",
  receivedOffers: "Teklif Aldıklarım",
  sentOffers: "Teklif Verdiklerim",
  myPurchases: "Satın Aldıklarım",
  quickOffers: "Hızlı Teklifler",
  offerPrice: "Teklif Fiyatı",
  orderStatus_1: "Teklif Verildi",
  orderStatus_2: "Teklif Onaylandı",
  orderStatus_3: "Satın Alındı",
  showProduct: "Ürünü Görüntüle",
  withdrawOffer: "Teklifi Geri Çek",
  rejectOffer: "Teklifi Reddet",
  acceptOffer: "Teklifi Onayla",
  noData: "Veri yok",
  saleOk: "Satın alma başarıyla gerçekleşti",
  makeBuy: "Satın alma işlemini gerçekleştir",
  success: "İşlem Başarıyla Gerçekleştirildi",
  ERR_EMAILINVALID: "E-Posta Geçersiz",
  thisProductIsSold: "Bu ürün satıldı",
  removeImage: "Resmi kaldır",
  ERR_PRODUCTNAMELONG: "Ürün ismi 100 karakterden uzun olamaz",
  ERR_PRODUCTDESCRIPTIONLONG: "Ürün açıklaması 500 karakterden uzun olamaz",
  ERR_CATEGORY_REQUIRED: "Ürün kategorisi seçilmesi zorunludur",
  ERR_USECASE_REQUIRED: "Ürün kullanım durumu seçilmesi zorunludur",
  ERR_LOGIN: "E-Posta adresiniz veya şifreniz yanlış",
  ERR_NO_SELECTED: "Resim seçilmedi, lütfen yüklemek istediğiniz resmi seçin",
  ERR_EMAIL_EXISTS: "Bu E-Posta adresi kayıtlıdır",
  ERR_NAME_SHORT: "İsim kısa",
  ERR_SURNAME_SHORT: "Soyisim kısa",
  noProduct: "Ürün yok",
  default: "Varsayılan",
  language: "Dil",
  theme: "Tema",
  loginSuccess: "Giriş başarılı",
  ERR_PRICE_REQUIRED: "Fiyat alanı doldurulması zorunludur",
};

export default language;
