var language = {
  appName: "Product Catalog",
  login: "Login",
  register: "Register",
  email: "E-Mail",
  password: "Password",
  passwordAgain: "Password (again)",
  name: "Name",
  surname: "Surname",
  productDetail: "Product Detail",
  en: "English (İngilizce)",
  tr: "Turkish (Türkçe)",
  addProduct: "Add Product",
  upload: "Upload",
  save: "Save",
  brand: "Brand",
  picture: "Picture",
  pleasePictureSelect: "Please select your product picture",
  category: "Category",
  color: "Color",
  useCase: "Use Case",
  select: "Select...",
  productName: "Product Name",
  productDescription: "Product Description",
  productPrice: "Product Price",
  yes: "Yes",
  no: "No",
  productIsOfferable: "Is Offerable",
  productIsSold: "Is Sold",
  ERR_EXTENSION: "File extension is not accepted",
  ERR_SIZE:
    "The size of the image you are trying to upload is larger than 400 KB",
  ERR_PASSWORD_NOT_EQUAL: "Password is not equal",
  ERR_PASSWORD_SHORT: "Password is short",
  ERR_PASSWORD_LONG: "Password is long",
  logout: "Log out",
  sendOffer: "Send Offer",
  buy: "Buy",
  priceSign: "$",
  user: "User",
  myAccount: "My Account",
  receivedOffers: "Received Offers",
  sentOffers: "Sent Offers",
  myPurchases: "My Purchases",
  quickOffers: "Quick Offers",
  offerPrice: "Offer Price",
  orderStatus_1: "Offered",
  orderStatus_2: "Offer Accepted",
  orderStatus_3: "Saled",
  showProduct: "Show Product",
  withdrawOffer: "Withdraw Offer",
  rejectOffer: "Reject Offer",
  acceptOffer: "Accept Offer",
  noData: "No data",
  saleOk: "Purchase done successfully",
  makeBuy: "Make your purchase",
  success: "Process Successfully",
  ERR_EMAILINVALID: "E-Mail Invalid",
  thisProductIsSold: "This product is sold",
  removeImage: "Remove Image",
  ERR_PRODUCTNAMELONG: "Product name is too long",
  ERR_PRODUCTDESCRIPTIONLONG: "Product description is too long",
  ERR_CATEGORY_REQUIRED: "Product category is required",
  ERR_USECASE_REQUIRED: "Product use case is required",
  ERR_LOGIN: "Your e-mail address or password is incorrect",
  ERR_NO_SELECTED:
    "No image selected, please select the image you want to upload",
  ERR_EMAIL_EXISTS: "E-Mail already exists",
  ERR_NAME_SHORT: "Name is short",
  ERR_SURNAME_SHORT: "Surname is short",
  noProduct: "No product",
  default: "Default",
  language: "Language",
  theme: "Theme",
  loginSuccess: "Login success",
  ERR_PRICE_REQUIRED: "Price is required",
};

export default language;
